### ISSUE TITLE
[DOCS] 회원 Swagger 문서화 작업

### ISSUE THREAD

**Issue by hyensukim** [daejangjangi/daejangjangi-BE#17]
## Description
- 회원 도메인 관련 Api Swagger 문서화 작업 진행.

## To-Do
- [x] Validation 오류 메시지 정의
- [x] JPA Auditing 생성일자/수정일자/생성자/수정자 추가
- [x] Swagger 문서화 진행
