### ISSUE TITLE
[FEAT] 응답 형식 및 예외 핸들링 설정 추가

### ISSUE THREAD

**Issue by hyensukim** [daejangjangi/daejangjangi-BE#2]
## Description
- 응답 형식 통일화
- 전역 예외 핸들링 처리

## To-Do
- [x] Custom Response 형식 클래스 정의
- [x] ErrorType Enum으로 정의
- [x] RestControllerAdvice, ExceptionHandler를 활용한 전역 예외처리

## ETC
