### ISSUE TITLE
[FEAT] 문의 및 FAQ 관련 API 구현부 수정

### ISSUE THREAD

**Issue by hyensukim** [daejangjangi/daejangjangi-BE#37]
## Description
- 요구사항 추가(문의하기)로 인한 FAQ API 구현 수정

## To-Do
- [x] 문의 및 FAQ 관련 ERD 수정
- [x] 문의 등록 API
- [x] 문의 삭제 API
- [x] 문의 답변 등록 API
- [x] 내 문의 목록 조회 API
- [x] FAQ 등록 API
- [x] FAQ 삭제 API
- [x] FAQ 목록 조회 API
