### ISSUE TITLE
[DOCS] Swagger 문서 수정

### ISSUE THREAD

**Issue by hyensukim** [daejangjangi/daejangjangi-BE#49]
## Description
- Swagger 문서 정리 및 오타 수정

## To-Do
- [ ] 문서화 관련 컨벤션 정리
- [ ] 회원 Swagger 문서
- [ ] 소셜 Swagger 문서
- [ ] FaQ Swagger 문서
- [ ] QnA Swagger 문서
- [ ] 대장툰 Swagger 문서
- [ ] 카드뉴스 Swagger 문서
- [ ] 뉴스레터 Swagger 문서
- [ ] 릴스 Swagger 문서
- [ ] 상품 Swagger 문서
- [ ] 게시판 Swagger 문서
- [ ] 게시글 Swagger 문서
