### ISSUE TITLE
[FEAT] CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by hyensukim** [daejangjangi/daejangjangi-BE#5]
## Description
- AWS CLI + Github Actions를 활용한 파이프라인 구축

![cicd 파이프라인 구축](https://github.com/user-attachments/assets/71d0443d-b20a-4d38-ba09-db5ccb5795a1)

## To-Do
- [x] EC2 내 Docker & Docker-Compose 환경 구축
- [x] Dockerfile 작성 및 Docker Hub에 추가
- [x] feat branch workflow script 테스트
- [x] slack notification 연동
- [x] 개발 서버 내 docker-compose.yml 작성
- [x] Github Actions script 작성 및 테스트
