### ISSUE TITLE
[FEAT] 마켓 : 상품 리스트 관련 API 구현

### ISSUE THREAD

**Issue by hyensukim** [daejangjangi/daejangjangi-BE#60]
## Description
- 상품 리스트 관련 API 구현

## To-Do
- [x] 최근 인기상품 조회 API 구현
- [x] 상품 추천 관련 API 구현(다른 응답 형식)
- [x] 베너 등록 API 구현
- [x] 베너 목록 조회 API 구현
- [x] 인기 검색어 API 구현
- [x] 상품 카테고리(마켓용) 설계 및 구현 추가
- [x] 상품 카테고리별 조회 API 구현
- [x] 상품 검색 API 구현
- [x] 상품 좋아요 등록/삭제 API 구현
- [x] 관심 상품 목록 조회(좋아요 생성 일자 내림차순)
- [x] 관심 상품 목록 조회 시 태그 추가
