### ISSUE TITLE
[FEAT] 배변 분석 API 구현

### ISSUE THREAD

**Issue by rosieisor** [daejangjangi/daejangjangi-BE#64]
## Description
- 배변 분석 API 구현

## To-Do
- [x] OpenFeign 환경 설정
- [x] 배변 분석 관련 엔티티 설계
- [x] 배변 이미지 분석 API 구현
- [x] 배변 진단 분석 API 구현
- [x] 배변 분석 결과 일지에 저장 API 구현
