### ISSUE TITLE
[FEAT] 배변 분석 관련 API 기능 수정

### ISSUE THREAD

**Issue by rosieisor** [daejangjangi/daejangjangi-BE#82]
## Description
- 배변 분석 관련 API 기능 수정

## To-Do
- [x] 배변 분석 결과 저장 시 배변 일지에 저장되지 않도록 수정
- [x] 배변 분석 결과 삭제 API 구현
- [x] 배변 분석 결과 목록 조회 API 구현
