### ISSUE TITLE
[BUG] 타임존 KST로 통일

### ISSUE THREAD

**Issue by rosieisor** [daejangjangi/daejangjangi-BE#87]
### mysql 타임존 KST로 변경

1️⃣ vim 설치
```
microdnf install -y vim
```

2️⃣ my.cnf 파일 수정
```
default-time-zone='Asia/Seoul'
```

3️⃣ mysql 컨테이너 재시작
```
sudo docker restart mysql
```

✔️ 변경 확인
``` 
date
```
<img width="405" alt="image" src="https://github.com/user-attachments/assets/132a1ecd-67b4-4d76-aaf2-d0487cc11301" />

### 백엔드 서버 컨테이너 타임존 KST로 변경

1️⃣ 타임존 변경 명령어
```
dpkg-reconfigure tzdata
```

✔️ 변경 확인
``` 
date
```
<img width="464" alt="image" src="https://github.com/user-attachments/assets/ceaddcc7-e8d3-424a-bae5-b116361fd672" />

### EC2 타임존 변경
```
sudo timedatectl set-timezone Asia/Seoul
```

### docker-compose 내 mysql 타임존(KST) 설정 추가
```
TZ=Asia/Seoul
```

✔️ 변경 확인
<img width="378" alt="image" src="https://github.com/user-attachments/assets/c26638ba-5e99-40d0-b8e8-a949f87ec482" />

## To-Do
- [x] mysql 컨테이너 KST로 변경
- [x] 백엔드 컨테이너 KST로 변경
- [x] JVM 타임존 KST로 변경
- [x] 생성일 및 배변 활동일 저장/조회 시 KST로 기준으로 통일
- [x] docker-compose 내 mysql 타임존(KST) 설정 추가

## ETC
- https://iruplace.tistory.com/255
